// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoFsg8QjYJBzfD4QvXmq_xB1wI98Qf05Q',
    appId: '1:719300857322:web:6aafe6b2a0740aec747693',
    messagingSenderId: '719300857322',
    projectId: 'menstrual-health-awareness-app',
    authDomain: 'menstrual-health-awareness-app.firebaseapp.com',
    storageBucket: 'menstrual-health-awareness-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3WYZyKZQMUotJl-FRPOnqGvPTYZjQSdM',
    appId: '1:719300857322:android:9b2ffacf1d4a8f25747693',
    messagingSenderId: '719300857322',
    projectId: 'menstrual-health-awareness-app',
    storageBucket: 'menstrual-health-awareness-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0O5xtu_8qBpkx5LjmxAqWZj8dz19OzCs',
    appId: '1:719300857322:ios:1e2f264c885ab089747693',
    messagingSenderId: '719300857322',
    projectId: 'menstrual-health-awareness-app',
    storageBucket: 'menstrual-health-awareness-app.firebasestorage.app',
    iosBundleId: 'com.example.menstrualHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0O5xtu_8qBpkx5LjmxAqWZj8dz19OzCs',
    appId: '1:719300857322:ios:1e2f264c885ab089747693',
    messagingSenderId: '719300857322',
    projectId: 'menstrual-health-awareness-app',
    storageBucket: 'menstrual-health-awareness-app.firebasestorage.app',
    iosBundleId: 'com.example.menstrualHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoFsg8QjYJBzfD4QvXmq_xB1wI98Qf05Q',
    appId: '1:719300857322:web:9a1aeda93b826015747693',
    messagingSenderId: '719300857322',
    projectId: 'menstrual-health-awareness-app',
    authDomain: 'menstrual-health-awareness-app.firebaseapp.com',
    storageBucket: 'menstrual-health-awareness-app.firebasestorage.app',
  );
}
